// import './es6-tutorial/lesson1.js'
// import './es6-tutorial/lesson2.js'
// import './es6-tutorial/lesson3.js'
// import lesson4 from './es6-tutorial/lesson4.js'
import 'babel-polyfill'
import lottery from './lottery'
